export const ERROR_MESSAGES = {
  AUTH: {
    EMAIL_PASSWORD_REQUIRED: 'Email and password are required',
    INVALID_CREDENTIALS: 'Invalid email or password',
    ACCOUNT_INACTIVE: 'Your account is inactive. Please contact support.',
    EMAIL_EXISTS: 'Email already registered',
    REGISTRATION_FAILED: 'Registration failed. Please try again.',
    WEAK_PASSWORD: 'Password must be at least 8 characters long and contain at least one uppercase letter, one lowercase letter, one number, and one special character (@$!%*?&)',
    USER_NOT_FOUND: 'User not found',
    INSUFFICIENT_PERMISSIONS: 'You do not have sufficient permissions',
    TOKEN_GENERATION_FAILED: 'Failed to generate authentication token',
    VALIDATION_FAILED: 'User validation failed',
    ROLE_VALIDATION_FAILED: 'Role validation failed',
    LOGIN_FAILED: 'Login failed. Please try again.'
  },
  TASKS: {
    NOT_FOUND: (id: string) => `Task with ID ${id} not found`,
    CREATE_FAILED: 'Failed to create task',
    FETCH_FAILED: 'Failed to fetch tasks',
    UPDATE_FAILED: 'Failed to update task',
    DELETE_FAILED: 'Failed to delete task',
    QUEUE_ERROR: 'Failed to queue task operation',
    CONFLICT: 'Task conflict detected',
    INVALID_PAGINATION: 'Invalid pagination parameters',
    STATS_FAILED: 'Failed to fetch task statistics',
    INVALID_BATCH_INPUT: 'Task IDs must be provided as an array',
    EMPTY_BATCH: 'No task IDs provided for batch operation',
    INVALID_ACTION: (action: string) => `Invalid batch action: ${action}`,
    BATCH_FAILED: 'Batch operation failed',
  },
};